image: node:12.13-alpine

unittest:
  stage: test
  script:
    - npm install
    - npm lint
    - npm test

production:
  type: deploy
  image: node:12.13-alpine
  script:
    - apt-get update -qy
    - apt-get install -yqq node-typescript --silent
    - dpl --provider=heroku --app=plmo1 --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
    - integration-heroku
