language: node_js
node_js:
  - '12.13'
before_install:
  - cd frontend
  - npm install
  - echo REACT_APP_BASE_APP=/back >> .env.production
  - npm run build
  - cd ../backend
  - npm install -g typescript@1.0
script:
  - npm run build
deploy:
  provider: heroku
  app: par-le-monde-1
  api_key:
    secure: "CtfbmoMrdfR4ELILNnxlkJrZRmh8TmAm5AvhIoePURQN0a11fK6LLSHjeylgyq/7cPTEDeZyy0u/urHlUMRJP4uefhlTtoWgdtGIYE7C5bhY60kyAaxAN0ukY37+3caEjQUkUfmbpR4H9fWFjih7iP6KQJ6cQq6zdyS4ZPB60He46Wjml2KibeKLBiRo8OKFPSI3Tu+xBi+ernK0qi+/u3elc6svVTl11lY4S66dYPj9FAEHiZXfUQdvi2G7w5Fgxs4kYxMbt46f2+vQ/xeyTS7It7fj5kG4Q6DoObP9RUJAOk4Qvt509HfaqDeOTILk5dK9ZSHgUyT/q5SxCJaK+4Ckp1WKuRAakZrXas794uAkOKpuXDfe7AiDEQB1X6dPxVR2ocdyb/8FY1JD937wYXAUoeHLT/SqQXjv0QR/rj2hm74E2comKSYzceH7bSYlWKRgNd6xJ0s4K3ZL9ZRR0M0AsxnM1UX+6a/K8fzy+NFA6HpJ/nJ6MRzeskRtIGRLOZwPFSb1eDjkuaiojsA/27vYBrJ2otyLdXNAQ3CQ1eYPoDKaWY69SJXT2miwDqaZOBT3kEKJRVoeeAXBISjpOxHtRW1lXHyDFZyfQfcd4ZNGYwB9hzQxGz55zCHMP3yrZqYCW4gO/+UXdbFmLSYbDXEv998/VIbzBJUNeR+Oxlo="
