language: node_js
node_js:
  - '12.13'
before_install:
  - cd backend
  - npm install -g typescript@1.0
script:
  - npm run build
deploy:
  provider: heroku
  api_key: heroku-api-key
  app: par-le-monde-1
