version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend/src:/usr/src/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    links:
      - mariaDB
    environment:
      - PRODUCTION=false
      - DEBUG=true
      - DB_HOST=mariaDB
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=password
    restart: always
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/dist:/usr/src/app/dist

  mariaDB:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./backend/mariaDB:/var/lib/mysql
