version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    restart: always
    environment:
      - REACT_APP_BASE_APP=http://localhost:5000
    volumes:
      - ./frontend/src:/usr/src/app/src

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    links:
      - mariaDB
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend/src:/usr/src/app/src

  mariaDB:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./backend/mariaDB:/var/lib/mysql
