version: '3.7'
services:
  plmo1:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "5000:5000"
    links:
      - mariaDB
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist

  mariaDB:
    image: mariadb:10.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mariaDB:/var/lib/mysql
