/projects:
  get:
    tags:
      - Projects
    summary: Returns list of user projects.
    security:
      - bearerAuth: []
    responses:
      200:
        description: A JSON array of user projects.
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Project"
      401:
        $ref: "#/components/responses/Unauthorized"
      403:
        $ref: "#/components/responses/Unauthorized2"
  post:
    tags:
      - Projects
    summary: Create a new project.
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - themeId
              - scenarioId
              - languageCode
              - title
              - questions
            properties:
              themeId:
                type: integer
                description: Project theme.
              scenarioId:
                type: integer
                description: Project scenario.
              languageCode:
                type: string
                description: Project language.
              title:
                type: string
                description: Project title.
              questions:
                type: array
                description: Project questions.
                items:
                  type: object
                  properties:
                    question:
                      type: string
                      description: question label.
    responses:
      200:
        description: The new project.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
      401:
        $ref: "#/components/responses/Unauthorized"
      403:
        $ref: "#/components/responses/Unauthorized2"
      500:
        $ref: "#/components/responses/InternalError"

/projects/{projectId}:
  get:
    tags:
      - Projects
    summary: Return the project with projectId.
    security:
      - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        description: The ID of the project to return.
        schema:
          type: integer
          format: int64
          minimum: 1
    responses:
      200:
        description: The JSON object project.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
      401:
        $ref: "#/components/responses/Unauthorized"
      403:
        $ref: "#/components/responses/Unauthorized2"
      404:
        $ref: "#/components/responses/NotFound"
  put:
    tags:
      - Projects
    summary: Update the project by projectId. Admin only.
    security:
      - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        description: The ID of the project to update.
        schema:
          type: integer
          format: int64
          minimum: 1
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - title
            properties:
              title:
                type: string
                description: Project title.
    responses:
      200:
        description: The updated project.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Project"
      401:
        $ref: "#/components/responses/Unauthorized"
      403:
        $ref: "#/components/responses/Unauthorized2"
      404:
        $ref: "#/components/responses/NotFound"
      500:
        $ref: "#/components/responses/InternalError"
  delete:
    tags:
      - Projects
    summary: Delete the project with projectId.
    security:
      - bearerAuth: []
    parameters:
      - name: projectId
        in: path
        required: true
        description: The ID of the project to delete.
        schema:
          type: integer
          format: int64
          minimum: 1
    responses:
      204:
        description: Project succesfully deleted.
      401:
        $ref: "#/components/responses/Unauthorized"
      403:
        $ref: "#/components/responses/Unauthorized2"
      500:
        $ref: "#/components/responses/InternalError"
